version: '3.8'

services:
  full_app_proxy:
    build:
      context: ./fullstack-app-proxy/
      args:
        NGINX_FILENAME: ${NGINX_FILENAME:-nginx-launch-app.conf}
    ports:
      - 8030:8030
    restart: always
    networks:
      fullstack_proxy:
        aliases:
          - frontend.full_app_proxy.com
          - backend.full_app_proxy.com
    depends_on:
      fastapi:
        condition: service_healthy
      vueapp_dev:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://vueapp_dev:5173
      interval: 60s
      timeout: 10s
      retries: 10
    logging:
      driver: none 
