version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=login
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_pwd
    secrets:
      - mysql_pwd
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

secrets:
  mysql_pwd:
    file: backend/docker_secrets/mysql_pwd.txt
