version: '3.8'

services:
  vueapp_test_e2e_cypress:
    networks:
      - fullstack_proxy
    build:
      context: .
      dockerfile: ./cypress.Dockerfile
    secrets:
      - mailslurp_api_key
    environment:
      - CYPRESS_BASE_URL=${CYPRESS_BASE_URL}
      - CYPRESS_VIDEO=${CYPRESS_VIDEO-true}
      - CYPRESS_TAGS=${CYPRESS_TAGS}
      - CYPRESS_VERIFY_TIMEOUT=${CYPRESS_VERIFY_TIMEOUT}
      - CYPRESS_apiUrl=${CYPRESS_apiUrl}
      - CYPRESS_adminApiUrl=${CYPRESS_adminApiUrl}
      - CYPRESS_adminApiLoginUsername=${CYPRESS_adminApiLoginUsername}
      - CYPRESS_adminApiLoginPassword=${CYPRESS_adminApiLoginPassword}
    depends_on:
      fastapi:
        condition: service_healthy
      vueapp_dev:
        condition: service_healthy
      full_app_proxy:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./cypress:/app/cypress

secrets:
  mailslurp_api_key:
    file: docker_secrets/mailslurp_api_key.txt
