name: Run Tests With Docker

on:
  push:
  workflow_dispatch:

jobs:
  frontend-unit-tests:
    name: Run Frontend module's unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Run frontend unit tests
        run: sudo ./scripts_docker.sh frontend unit-tests

  frontend-e2e-tests-cypress:
    name: Run Frontend Cypress based E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: mg-login-examples/login-backend-fastapi
          path: backend
      - name: Add mysql password text file for a test mysql container
        run: echo "password_1" > backend/docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password_2" > backend/docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password_3" > backend/docker_secrets/redis_pwd.txt
      - name: Add github secret mailslurp api key as a text file used as a docker secret
        run: 'echo "$MAILSLURP_API_KEY" > docker_secrets/mailslurp_api_key.txt'
        shell: bash
        env:
          MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
      - name: Run cypress e2e tests
        run: ./scripts_docker.sh run-e2e-tests-cypress

  frontend-e2e-tests-playwright:
    name: Run Frontend Playwright based E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: mg-login-examples/login-backend-fastapi
          path: backend
      - name: Add mysql password text file for a test mysql container
        run: echo "password_1" > backend/docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password_2" > backend/docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password_3" > backend/docker_secrets/redis_pwd.txt
      - name: Run cypress e2e tests
        run: ./scripts_docker.sh run-e2e-tests-playwright
